version: "3.3"

services:

  web:
    image: nginx:1.17
    ports:
      - 80:80
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs:/var/log/nginx
    depends_on:
      - php
      - mariadb

  php:
    image: prooph/php:7.4-fpm
    volumes:
      - ./www:/var/www
      - ./php/:/usr/local/etc/php/
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.4
    restart: always
    command: "mysqld --init-file /data/application/init.sql"
    volumes:
      - ./mariadb-data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

volumes:
  mariadb-data:
